### ISSUE TITLE
Can't install!

### ISSUE THREAD

**Issue by noc2art** [kabushPasha/HoudiniSD#1]
Hi;

Although I placed both the "Houdinisd_package.Json" file and  "houdinisd*" folder to C:\Program Files\Side Effects Software\Houdini 19.5\packages like you instructed, I can't get the examples file to work. Something's wrong but I can't figure out what :-/

![image](https://github.com/kabushPasha/HoudiniSD/assets/32395664/d5895554-4cd0-4d13-9984-3b5952f9deaa)

Could you tell me what I might have done wrong?

Cheers;

AJ

**Comment by kabushPasha** [comment]
Hi!
Unfortunately most of the nodes were written with @bindings which were added only in houdini 20.

Thanks for pointing it out, Ill add it to the description
